{% set name = "kbatch" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kbatch-{{ version }}.tar.gz
  sha256: 6a8b289ef66e1eee44394621888a7bc4f297ce287ce595c330e43f19958117fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - kbatch = kbatch.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - rich
    - httpx
    - pyyaml
    - python-kubernetes

test:
  imports:
    - kbatch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kbatch-dev/kbatch
  summary: Submit batch jobs to Kubernetes.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
